### ISSUE TITLE
Interrupts issue

### ISSUE THREAD

**Issue by aliraza1944** [aliraza1944/esp_key#1]
Hi @nkolban.

I have been following your ESP32 related tutorials. I have written a code to interface PS2 keyboard with ESP32. I am having a small issue with the code and it seems that there is some sort of latency in interrupt processing due to which I am unable  to read the Data line correctly. I have explained the issue in detail in the README file.

I have copied the interrupt routine from your ESP32 snippets repo.

Any help would be greatly appreciated.

Regards

**Comment by nkolban** [comment]
Howdy ... I'll be happy to try and assist.  I work on ESP32s in the evening and weekends (US central time).  I'll study your write up ... but chances are we'll have to chat and/or instant message.

**Comment by aliraza1944** [comment]
Thank you for your interest, I resolved the issue an hour ago. Eliminated xQueueSendToBackFromISR from the handler and took care of the execution of the interrupt inside the handler. I will merge the branch to master in a few hours. You can take a look if you find any discrepancies.
